### ISSUE TITLE
Error from Karma: TypeError: Data must be a string or a buffer

### ISSUE THREAD

**Issue by leifwells** [DomesticApp/ionic-test-doubles#1]
This library is a great idea, but I can't get it working with my project.

I installed using `npm install ionic-test-doubles --save-dev`

For some reason, I am unable to get this recognized by my IDE:
```
import { PlatformStub } from 'ionic-test-doubles';
```
I found that this does get recognized:
```
import { PlatformStub } from 'ionic-test-doubles/dist/index';
```

Here's the test:
```
import { async, ComponentFixture, TestBed } from '@angular/core/testing';
import { By }           from '@angular/platform-browser';
import { DebugElement } from '@angular/core';
import { Page1 } from './page1';
import { IonicModule, Platform, NavController} from 'ionic-angular/index';
import { StatusBar } from '@ionic-native/status-bar';
import { SplashScreen } from '@ionic-native/splash-screen';
import { PlatformMock, StatusBarMock, SplashScreenMock } from '../../../test-config/mocks-ionic';
import { PlatformStub } from 'ionic-test-doubles/dist/index';

describe('Page1', function() {
  let de: DebugElement;
  let comp: Page1;
  let fixture: ComponentFixture<Page1>;

  beforeEach(async(() => {
    TestBed.configureTestingModule({
      declarations: [Page1],
      imports: [
        IonicModule.forRoot(Page1)
      ],
      providers: [
        NavController,
        { provide: Platform, useClass: PlatformStub},
        { provide: StatusBar, useClass: StatusBarMock },
        { provide: SplashScreen, useClass: SplashScreenMock },
      ]
    });
  }));

  beforeEach(() => {
    fixture = TestBed.createComponent(Page1);
    comp = fixture.componentInstance;
    de = fixture.debugElement.query(By.css('h3'));
  });

  it('should create component', () => expect(comp).toBeDefined());

  it('should have expected <h3> text', () => {
    fixture.detectChanges();
    const h3 = de.nativeElement;
    expect(h3.innerText).toMatch(/ionic/i,
      '<h3> should say something about "Ionic"');
  });
});
```

When I attempt to use it, I get this really odd error:
```
ts-loader: Using typescript@2.3.3 and /Users/leifwells/Code/driftyco/ionic-unit-testing-example/tsconfig.json
27 05 2017 20:24:08.855:ERROR [karma]: TypeError: Data must be a string or a buffer
    at TypeError (native)
    at Hash.update (crypto.js:74:16)
    at HarmonyExportImportedSpecifierDependency.updateHash (/Users/leifwells/Code/driftyco/ionic-unit-testing-example/node_modules/webpack/lib/dependencies/HarmonyExportImportedSpecifierDependency.js:144:8)
    at /Users/leifwells/Code/driftyco/ionic-unit-testing-example/node_modules/webpack/lib/DependenciesBlock.js:33:5
    at Array.forEach (native)
    at NormalModule.DependenciesBlock.updateHash (/Users/leifwells/Code/driftyco/ionic-unit-testing-example/node_modules/webpack/lib/DependenciesBlock.js:32:20)
    at NormalModule.Module.updateHash (/Users/leifwells/Code/driftyco/ionic-unit-testing-example/node_modules/webpack/lib/Module.js:162:41)
    at NormalModule.updateHash (/Users/leifwells/Code/driftyco/ionic-unit-testing-example/node_modules/webpack/lib/NormalModule.js:327:30)
    at modules.forEach.m (/Users/leifwells/Code/driftyco/ionic-unit-testing-example/node_modules/webpack/lib/Chunk.js:253:31)
    at Array.forEach (native)
    at Chunk.updateHash (/Users/leifwells/Code/driftyco/ionic-unit-testing-example/node_modules/webpack/lib/Chunk.js:253:16)
    at Compilation.createHash (/Users/leifwells/Code/driftyco/ionic-unit-testing-example/node_modules/webpack/lib/Compilation.js:1121:10)
    at sealPart2 (/Users/leifwells/Code/driftyco/ionic-unit-testing-example/node_modules/webpack/lib/Compilation.js:605:9)
    at Compilation.applyPluginsAsyncSeries (/Users/leifwells/Code/driftyco/ionic-unit-testing-example/node_modules/tapable/lib/Tapable.js:131:46)
    at Compilation.seal (/Users/leifwells/Code/driftyco/ionic-unit-testing-example/node_modules/webpack/lib/Compilation.js:570:8)
    at /Users/leifwells/Code/driftyco/ionic-unit-testing-example/node_modules/webpack/lib/Compiler.js:474:16
npm ERR! Test failed.  See above for more details.
```
Let me know if I am doing anything wrong or if you have questions.

Leif @leifwells

**Comment by jaalzateolaya** [comment]
Excuse me @leifwells, I haven't realized that you posted this issue... Did the last release solve the problem? I found out that the library wasn't linked well but now is working for me.

Thank you so much for your feedback and I hope this library is still being useful for you.
